import {
  Activity,
  BookOpen,
  Bot,
  Briefcase,
  Calendar,
  ChartLine,
  Clock,
  Code,
  Compass,
  Database,
  FileText,
  Gauge,
  Globe,
  GraduationCap,
  Handshake,
  HeartPulse,
  House,
  Layers,
  LayoutDashboard,
  Lightbulb,
  ListChecks,
  Mail,
  MapPin,
  Megaphone,
  MousePointerClick,
  Palette,
  PenLine,
  Plane,
  Plug,
  Repeat,
  Rocket,
  Scale,
  ScanText,
  Search,
  Send,
  Share2,
  Shield,
  ShoppingCart,
  Sparkles,
  Store,
  Target,
  TrendingUp,
  User,
  Users,
  UtensilsCrossed,
  Workflow,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/content/types";

/** Single stroke width everywhere, per the design system. */
export const ICON_STROKE = 1.75;

const map: Record<IconName, LucideIcon> = {
  search: Search,
  target: Target,
  megaphone: Megaphone,
  mail: Mail,
  "map-pin": MapPin,
  "share-2": Share2,
  "pen-line": PenLine,
  "trending-up": TrendingUp,
  code: Code,
  "layout-dashboard": LayoutDashboard,
  bot: Bot,
  workflow: Workflow,
  "file-text": FileText,
  plug: Plug,
  sparkles: Sparkles,
  palette: Palette,
  globe: Globe,
  "heart-pulse": HeartPulse,
  house: House,
  "shopping-cart": ShoppingCart,
  "graduation-cap": GraduationCap,
  plane: Plane,
  "utensils-crossed": UtensilsCrossed,
  briefcase: Briefcase,
  rocket: Rocket,
  store: Store,
  compass: Compass,
  layers: Layers,
  shield: Shield,
  gauge: Gauge,
  zap: Zap,
  users: Users,
  clock: Clock,
  "chart-line": ChartLine,
  "mouse-pointer-click": MousePointerClick,
  activity: Activity,
  lightbulb: Lightbulb,
  repeat: Repeat,
  database: Database,
  calendar: Calendar,
  "book-open": BookOpen,
  "list-checks": ListChecks,
  "scan-text": ScanText,
  send: Send,
  handshake: Handshake,
  scale: Scale,
  user: User,
};

export function Icon({ name, className = "h-5 w-5" }: { name: IconName; className?: string }) {
  const C = map[name];
  return <C className={className} strokeWidth={ICON_STROKE} aria-hidden="true" />;
}
