/**
 * Generates supabase/migrations/20261005000005_import_existing_content.sql
 * from the site's existing content/*.ts files, so the CMS starts with exactly
 * the content that is live today (no invented copy, no fake numbers).
 *
 *   npm run cms:generate-import
 *
 * Every insert uses ON CONFLICT DO NOTHING, so re-running never overwrites CMS edits.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { aiHub, aiPages } from "../content/ai";
import { blogCategories, blogPage, posts, readingMinutes } from "../content/blog";
import { developmentHub, developmentPages } from "../content/development";
import { hero } from "../content/home";
import { industriesPage } from "../content/industries";
import { locationsPage } from "../content/locations";
import { marketingHub, marketingPages } from "../content/marketing";
import { aboutPage, contactPage, servicesOverview } from "../content/pages";
import { productsPage } from "../content/products";
import { footerNav, site } from "../content/site";
import { socialLinks } from "../content/links";
import { workPage } from "../content/work";
import type { BlogPost } from "../content/types";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const qa = (arr: string[]) => `array[${arr.map(q).join(", ")}]::text[]`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

type Node = { type: string; attrs?: Record<string, unknown>; content?: Node[]; text?: string };
const text = (t: string): Node => ({ type: "text", text: t });
const para = (t: string): Node => ({ type: "paragraph", content: [text(t)] });

function postToDoc(post: BlogPost): Node {
  const content: Node[] = [];
  for (const s of post.sections) {
    content.push({ type: "heading", attrs: { level: 2, id: s.id }, content: [text(s.heading)] });
    for (const p of s.paragraphs) content.push(para(p));
    if (s.list) {
      content.push({
        type: s.ordered ? "orderedList" : "bulletList",
        ...(s.ordered ? { attrs: { start: 1 } } : {}),
        content: s.list.map((li) => ({ type: "listItem", content: [para(li)] })),
      });
    }
  }
  return { type: "doc", content };
}

const out: string[] = [];
out.push(`-- =====================================================================
--  Pytron Digital CMS — 5/5 — Import of the content that is live today
--  GENERATED by scripts/generate-content-import.ts — do not edit by hand.
--  Uses ON CONFLICT DO NOTHING: re-running never overwrites CMS edits.
-- =====================================================================
`);

// ---- Blog categories ----
out.push("-- Blog categories");
blogCategories.forEach((c, i) => {
  out.push(
    `insert into public.blog_categories (name, slug, sort_order) values (${q(c.name)}, ${q(c.slug)}, ${i}) on conflict do nothing;`,
  );
});

// ---- Blog posts ----
out.push("\n-- Blog posts");
// All posts share a publish date; keep the original editorial order (first = newest)
// by giving each a time on that day.
posts.forEach((p, i) => {
  const time = `${String(12 - Math.floor(i / 60)).padStart(2, "0")}:${String(59 - (i % 60)).padStart(2, "0")}:00`;
  const cat = blogCategories.find((c) => c.name === p.category);
  out.push(`insert into public.blogs (title, slug, excerpt, intro, content, author_name, category_id, status, published_at,
  seo_title, seo_description, reading_minutes, cta, created_at, updated_at)
values (${q(p.title)}, ${q(p.slug)}, ${q(p.description)}, ${q(p.intro)}, ${json(postToDoc(p))}, ${q(p.author)},
  (select id from public.blog_categories where slug = ${q(cat?.slug ?? "business-growth")}), 'PUBLISHED', ${q(`${p.date}T${time}Z`)},
  '', '', ${readingMinutes(p)}, ${q(p.cta === "web" || p.cta === "ai" ? p.cta : "marketing")},
  ${q(`${p.date}T${time}Z`)}, ${q(`${p.date}T${time}Z`)})
on conflict (slug) do nothing;`);
});

// ---- Services ----
out.push("\n-- Services");
const pillars = [
  ["marketing", marketingPages],
  ["web", developmentPages],
  ["ai", aiPages],
] as const;
for (const [pillar, pages] of pillars) {
  pages.forEach((s, i) => {
    out.push(`insert into public.services (pillar, name, slug, short_description, hero_heading, intro, icon, features,
  sort_order, status, published_at, seo_title, seo_description)
values (${q(pillar)}, ${q(s.label)}, ${q(s.slug)}, ${q(s.summary)}, ${q(s.h1)}, ${q(s.intro)}, ${q(s.icon)}, ${qa(s.included)},
  ${(i + 1) * 10}, 'PUBLISHED', '2026-10-04T00:00:00Z', ${q(s.meta.title)}, ${q(s.meta.description)})
on conflict (pillar, slug) do nothing;`);
  });
}

// ---- Built-in pages (hero copy + SEO; layout stays in code) ----
out.push("\n-- Built-in pages");
const system: {
  key: string;
  title: string;
  heading: string;
  description: string;
  meta: { title: string; description: string };
}[] = [
  {
    key: "home",
    title: "Home",
    heading: `${hero.h1Lines[0]}\n${hero.h1Lines[1]} [[${hero.h1Highlight}]]`,
    description: hero.copy,
    meta: {
      title: "Pytron Digital — Digital Marketing, Web Development & AI Automation",
      description:
        "Pytron Digital is a growth and technology partner: SEO, Google Ads, websites, web apps and AI automation from one team, for businesses in the USA, UK, Canada, Australia, UAE and India.",
    },
  },
  { key: "about", title: "About", heading: aboutPage.h1, description: aboutPage.intro, meta: aboutPage.meta },
  { key: "services", title: "Services", heading: servicesOverview.h1, description: servicesOverview.intro, meta: servicesOverview.meta },
  { key: "contact", title: "Contact", heading: contactPage.h1, description: contactPage.intro, meta: contactPage.meta },
  { key: "blog", title: "Blog", heading: blogPage.h1, description: blogPage.intro, meta: blogPage.meta },
  { key: "products", title: "Products", heading: productsPage.h1, description: productsPage.intro, meta: productsPage.meta },
  { key: "work", title: "Our Work", heading: workPage.h1, description: workPage.intro, meta: workPage.meta },
  { key: "industries", title: "Industries", heading: industriesPage.h1, description: industriesPage.intro, meta: industriesPage.meta },
  { key: "locations", title: "Markets We Serve", heading: locationsPage.h1, description: locationsPage.intro, meta: locationsPage.meta },
  { key: "digital-marketing", title: "Digital Marketing", heading: marketingHub.h1, description: marketingHub.intro, meta: marketingHub.meta },
  { key: "web-development", title: "Web Development", heading: developmentHub.h1, description: developmentHub.intro, meta: developmentHub.meta },
  { key: "ai-solutions", title: "AI Solutions", heading: aiHub.h1, description: aiHub.intro, meta: aiHub.meta },
];
for (const s of system) {
  out.push(`insert into public.pages (title, slug, system_key, status, hero_heading, hero_description, seo_title, seo_description, published_at)
values (${q(s.title)}, ${q(s.key)}, ${q(s.key)}, 'PUBLISHED', ${q(s.heading)}, ${q(s.description)}, ${q(s.meta.title)}, ${q(s.meta.description)}, '2026-10-04T00:00:00Z')
on conflict do nothing;`);
}

// ---- Footer navigation ----
out.push("\n-- Footer navigation");
const navCols = [
  ["footer_services", footerNav.services],
  ["footer_solutions", footerNav.solutions],
  ["footer_company", footerNav.company],
  ["footer_legal", footerNav.legal],
] as const;
out.push("do $$ begin if not exists (select 1 from public.navigation_items) then");
for (const [loc, items] of navCols) {
  items.forEach((l, i) => {
    const external = "external" in l && Boolean(l.external);
    out.push(
      `  insert into public.navigation_items (location, label, href, is_external, sort_order) values (${q(loc)}, ${q(l.label)}, ${q(l.href)}, ${external}, ${(i + 1) * 10});`,
    );
  });
}
out.push("end if; end $$;");

// ---- Site settings ----
out.push("\n-- Site settings (only fills empty values)");
out.push(`update public.site_settings set
  contact_email    = case when contact_email = '' then ${q(site.contact.email)} else contact_email end,
  contact_phone    = case when contact_phone = '' then ${q(site.contact.phoneDisplay)} else contact_phone end,
  whatsapp_url     = case when whatsapp_url = '' then ${q(site.contact.whatsapp)} else whatsapp_url end,
  social_linkedin  = case when social_linkedin = '' then ${q(socialLinks.linkedin)} else social_linkedin end,
  social_instagram = case when social_instagram = '' then ${q(socialLinks.instagram)} else social_instagram end,
  social_facebook  = case when social_facebook = '' then ${q(socialLinks.facebook)} else social_facebook end,
  social_x         = case when social_x = '' then ${q(socialLinks.x)} else social_x end,
  social_youtube   = case when social_youtube = '' then ${q(socialLinks.youtube)} else social_youtube end
where id = 1;`);

// The import runs as the migration owner, so it is attributed to "system" in the audit log.
// Remove those bootstrap entries so the activity feed starts clean.
out.push("\ndelete from public.audit_logs where user_id is null and user_email = 'system' and action in ('create', 'update');");

const dir = join(__dirname, "..", "supabase", "migrations");
const file = join(dir, "20261005000005_import_existing_content.sql");
writeFileSync(file, out.join("\n") + "\n");
console.log(`Wrote ${file}`);

// One-file version of all migrations, for pasting into the Supabase SQL editor.
const parts = readdirSync(dir)
  .filter((f) => f.endsWith(".sql"))
  .sort()
  .map((f) => `-- >>>>>>>>>>>>>>>>>>>> ${f}\n${readFileSync(join(dir, f), "utf8")}`);
const setup = join(__dirname, "..", "supabase", "setup.sql");
writeFileSync(
  setup,
  `-- Pytron Digital CMS — complete database setup (all migrations in order).\n-- GENERATED by scripts/generate-content-import.ts. Safe to run more than once.\n-- Paste into Supabase → SQL Editor → New query → Run.\n\n${parts.join("\n\n")}`,
);
console.log(`Wrote ${setup}`);
